"""
Test script for PoC 1: Cyber Brain — Zotero Annotation Injection.

Verifies that the auto-annotation library can successfully:
1. Extract text coordinates from a PDF using PyMuPDF
2. Inject highlight annotations via Zotero Web API
3. Correctly transform coordinates for Zotero's PDF reader

Usage:
    conda activate jarvis
    pip install -e .
    python tests/test_zotero_highlight.py
"""

import sys

from stable_jarvis_dev import ZoteroAnnotator, AnnotationResult

# ─────────────────────────────────────────────
# TEST CONFIGURATION
# ─────────────────────────────────────────────
PDF_PATH = (
    r"D:\Documents\Zotero\storage\SNX599P2"
    r"\Liu 等 - 2025 - RESC A Reinforcement Learning Based Search-to-Control"
    r" Planning Framework for Agile Quadrotors.pdf"
)
ATTACHMENT_KEY = "SNX599P2"
TARGET_TEXT = "The action produced by RL policy is"
PAGE_INDEX = 3


def main():
    print("=" * 60)
    print("PoC 1: Cyber Brain — Zotero Annotation Injection Test")
    print("=" * 60)
    print(f"\nPDF: {PDF_PATH}")
    print(f"Attachment Key: {ATTACHMENT_KEY}")
    print(f"Target Text: {TARGET_TEXT!r}")
    print(f"Page Index: {PAGE_INDEX}")
    print()

    # Create annotator instance
    annotator = ZoteroAnnotator()

    # Add highlight annotation
    print("Creating highlight annotation...")
    result: AnnotationResult = annotator.highlight(
        pdf_path=PDF_PATH,
        attachment_key=ATTACHMENT_KEY,
        target_text=TARGET_TEXT,
        page_index=PAGE_INDEX,
        comment="Auto-generated by Cyber Brain PoC 1",
        color="#ffd400",
    )

    if result.success:
        print(f"\n✅ Success!")
        print(f"   Annotation Key: {result.annotation_key}")
        print(f"   Extraction Method: {result.match.method}")
        print(f"   Page Dimensions: {result.match.page_width:.0f} x {result.match.page_height:.0f} pt")
        print(f"   Rectangles: {len(result.match.rects)}")
        for i, rect in enumerate(result.match.rects):
            print(f"     [{i}] x0={rect[0]:.2f}, y0={rect[1]:.2f}, x1={rect[2]:.2f}, y1={rect[3]:.2f}")
        print("\n→ Open Zotero, sync, and verify the highlight in the PDF reader.")
    else:
        print(f"\n❌ Failed: {result.error}")
        return 1

    print("\n" + "=" * 60)
    return 0


if __name__ == "__main__":
    sys.exit(main())
